# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9c2f7ec9652a7749112e2a42ad7fc5ffdf068b829e9959dafb82e46d112cf4b3e608bc585c6b59a6e8889dad18d1b3d589c344de5a67d912d1339af15c3b3f5

test:
  secret_key_base: 82198a887c341f73c73fb46347924ddf007e6c4e5a0f45c091202a400f43f0bda6f3f530bda685c129eca78c83f96cee8828920c63479a43629b192fc0c7f077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
